// Unique ID constraints for key node types
CREATE CONSTRAINT paper_id IF NOT EXISTS FOR (n:Paper) REQUIRE n.nodeId IS UNIQUE;
CREATE CONSTRAINT repo_ref_id IF NOT EXISTS FOR (n:RepositoryReferences) REQUIRE n.nodeId IS UNIQUE;
CREATE CONSTRAINT task_id IF NOT EXISTS FOR (n:Task) REQUIRE n.nodeId IS UNIQUE;
CREATE CONSTRAINT dataset_id IF NOT EXISTS FOR (n:Dataset) REQUIRE n.nodeId IS UNIQUE;
CREATE CONSTRAINT method_id IF NOT EXISTS FOR (n:Method) REQUIRE n.nodeId IS UNIQUE;
CREATE CONSTRAINT model_id IF NOT EXISTS FOR (n:Model) REQUIRE n.nodeId IS UNIQUE;
CREATE CONSTRAINT category_id IF NOT EXISTS FOR (n:Category) REQUIRE n.nodeId IS UNIQUE;
CREATE CONSTRAINT area_id IF NOT EXISTS FOR (n:Area) REQUIRE n.nodeId IS UNIQUE;
